name: GitHub Actions
run-name: integrationTesting

#设置触发时机
on:
  pull_request:
    branches: [ main ]

#每个 workflow 由多个 job 组成
#默认并行运行
jobs:
  unit-test:
    runs-on: ubuntu-latest
    # 定义任务的步骤 串行
    steps:
      # 将仓库的代码检出到当前工作目录中
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: angular-test
        # 执行shell命令
        run: |
          pwd # 打印当前工作目录
          cd web-app # 切换到 web 目录
          env # 显示环境变量信息
          npm install # 安装 Node.js 依赖
          # 运行angular 单元测试
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          # 构建 Angular 应用
          npm run build

  dingding-error:
    runs-on: ubuntu-latest
    needs: [ unit-test ]
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v4
      - name: Send dingding notify error
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{env.token}} #钉钉token
          body: |
            {
              "msgtype": "text",
              "text": {
                  "content": '[打叉][打叉][打叉]  执行失败\n提交者: ${{ github.triggering_actor }}\n任务: ${{ github.event.pull_request.title }}\n${{ github.ref_type }}: ${{ github.head_ref }}\n${{ github.event_name }}: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}'
             }
      }


    dingding-success:
      runs-on: ubuntu-latest
      if: ${{ success() }}
      needs: [ unit-test ]
      steps:
        - uses: actions/checkout@v4
        - name: Send dingding notify success
          uses: zcong1993/actions-ding@master
          with:
            dingToken: ${{env.token}} #钉钉token
            body: |
              {
               "msgtype": "text",
               "text": {
                   "content": '[微笑][微笑][微笑]  执行成功\n提交者: ${{ github.triggering_actor }}\n任务: ${{ github.event.pull_request.title }}\n${{ github.ref_type }}: ${{ github.head_ref }}\n${{ github.event_name }}: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}'
               }
              }
